name: Java CI with Maven

on:
  push:
    branches: [ "develop", "feature/**" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Verify Backend folder exists
      run: |
        echo "=== Checking project structure ==="
        ls -la
        echo "=== Backend folder ==="
        ls -la Backend/
        echo "=== pom.xml ==="
        cat Backend/pom.xml | head -10
        
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Compile Spring Boot Application
      run: |
        echo "=== STARTING COMPILATION ==="
        cd Backend
        mvn clean compile -DskipTests
        echo "=== COMPILATION FINISHED ==="
        
    - name: Verify JAR was created
      run: |
        echo "=== Checking if build was successful ==="
        ls -la Backend/target/ || echo "Target folder not found - BUILD FAILED"
